import type { Agent, EvalMetric, Session } from './types';

export const mockAgents: Agent[] = [
  {
    id: 'agent-general',
    name: '通用智能体',
    type: 'general',
    description: '处理常规任务、目标分解与知识检索',
    capabilities: ['对话理解', '任务规划', '知识检索'],
    status: 'idle',
  },
  {
    id: 'agent-research',
    name: '研究分析',
    type: 'research',
    description: '用于文献检索、研究总结与报告生成',
    capabilities: ['文献检索', '数据挖掘', '报告生成'],
    status: 'idle',
  },
  {
    id: 'agent-biochem',
    name: '生化分析',
    type: 'biochem',
    description: '聚焦蛋白质分析、分子模拟与生化计算',
    capabilities: ['序列分析', '结构预测', '通路分析'],
    status: 'active',
  },
  {
    id: 'agent-data',
    name: '数据科学',
    type: 'data-analysis',
    description: '执行统计分析、可视化与预测任务',
    capabilities: ['统计分析', '可视化', '预测分析'],
    status: 'idle',
  },
  {
    id: 'agent-code',
    name: '代码专家',
    type: 'code-expert',
    description: '负责代码生成、调试与重构建议',
    capabilities: ['代码生成', '错误诊断', '性能优化'],
    status: 'idle',
  },
];

export const mockSessions: Session[] = [
  {
    id: 'session-1',
    title: '蛋白质序列同源性分析',
    status: 'executing',
    selectedAgent: 'agent-biochem',
    messages: [
      {
        id: 'msg-1',
        role: 'user',
        content: '分析以下蛋白质序列的同源性，并预测其功能域结构。',
        timestamp: new Date(Date.now() - 600000),
      },
      {
        id: 'msg-2',
        role: 'system',
        content: '已选择生化分析智能体，正在生成执行计划。',
        timestamp: new Date(Date.now() - 580000),
      },
      {
        id: 'msg-3',
        role: 'agent',
        content: '计划已生成，包含 4 个步骤。请审核后批准执行。',
        timestamp: new Date(Date.now() - 570000),
        metadata: { agentId: 'agent-biochem' },
      },
    ],
    plan: {
      id: 'plan-1',
      goal: '蛋白质序列同源性分析与功能域预测',
      steps: [
        {
          id: 'step-1',
          title: '序列预处理',
          description: '验证序列格式、清洗数据并标准化编码',
          status: 'completed',
          assignedAgent: 'agent-biochem',
          startTime: new Date(Date.now() - 500000),
          endTime: new Date(Date.now() - 480000),
          output: '序列长度 342 aa，格式 FASTA，无异常字符。',
        },
        {
          id: 'step-2',
          title: 'BLAST 同源性搜索',
          description: '在 UniProt 数据库执行同源序列搜索',
          status: 'running',
          assignedAgent: 'agent-biochem',
          startTime: new Date(Date.now() - 480000),
        },
        {
          id: 'step-3',
          title: '功能域识别',
          description: '使用保守域扫描识别功能模块',
          status: 'pending',
          assignedAgent: 'agent-biochem',
        },
        {
          id: 'step-4',
          title: '结果整合与报告',
          description: '汇总分析结果并生成结构化结论',
          status: 'pending',
          assignedAgent: 'agent-biochem',
        },
      ],
      status: 'executing',
      createdAt: new Date(Date.now() - 600000),
      updatedAt: new Date(Date.now() - 10000),
      currentStepIndex: 1,
    },
    planHistory: [
      {
        id: 'plan-1',
        goal: '蛋白质序列同源性分析与功能域预测',
        steps: [
          {
            id: 'step-1',
            title: '序列预处理',
            description: '验证序列格式、清洗数据并标准化编码',
            status: 'completed',
            assignedAgent: 'agent-biochem',
          },
          {
            id: 'step-2',
            title: 'BLAST 同源性搜索',
            description: '在 UniProt 数据库执行同源序列搜索',
            status: 'running',
            assignedAgent: 'agent-biochem',
          },
          {
            id: 'step-3',
            title: '功能域识别',
            description: '使用保守域扫描识别功能模块',
            status: 'pending',
            assignedAgent: 'agent-biochem',
          },
          {
            id: 'step-4',
            title: '结果整合与报告',
            description: '汇总分析结果并生成结构化结论',
            status: 'pending',
            assignedAgent: 'agent-biochem',
          },
        ],
        status: 'executing',
        createdAt: new Date(Date.now() - 600000),
        updatedAt: new Date(Date.now() - 10000),
        currentStepIndex: 1,
      },
    ],
    traces: [
      {
        id: 'trace-1',
        stepId: 'step-1',
        timestamp: new Date(Date.now() - 500000),
        type: 'log',
        message: '开始序列预处理',
      },
      {
        id: 'trace-2',
        stepId: 'step-1',
        timestamp: new Date(Date.now() - 490000),
        type: 'success',
        message: '序列验证完成',
        details: { length: 342, format: 'FASTA' },
      },
      {
        id: 'trace-3',
        stepId: 'step-2',
        timestamp: new Date(Date.now() - 480000),
        type: 'log',
        message: '连接 UniProt BLAST 服务',
      },
      {
        id: 'trace-4',
        stepId: 'step-2',
        timestamp: new Date(Date.now() - 460000),
        type: 'log',
        message: '搜索进度 45%，预计剩余 30s',
      },
    ],
    memory: [
      {
        key: 'input_sequence_id',
        value: 'SEQ_20260323_001',
        timestamp: new Date(Date.now() - 500000),
        source: 'step-1',
      },
      {
        key: 'sequence_length',
        value: '342',
        timestamp: new Date(Date.now() - 490000),
        source: 'step-1',
      },
      {
        key: 'blast_job_id',
        value: 'BLAST_JOB_7f8e9d',
        timestamp: new Date(Date.now() - 480000),
        source: 'step-2',
      },
    ],
    createdAt: new Date(Date.now() - 600000),
    updatedAt: new Date(Date.now() - 10000),
  },
  {
    id: 'session-2',
    title: '研究文献综述生成',
    status: 'completed',
    selectedAgent: 'agent-research',
    messages: [],
    planHistory: [],
    traces: [],
    memory: [],
    createdAt: new Date(Date.now() - 86400000),
    updatedAt: new Date(Date.now() - 7200000),
  },
  {
    id: 'session-3',
    title: '数据可视化分析',
    status: 'draft',
    selectedAgent: 'agent-data',
    messages: [],
    planHistory: [],
    traces: [],
    memory: [],
    createdAt: new Date(Date.now() - 3600000),
    updatedAt: new Date(Date.now() - 3600000),
  },
];

export const mockEvalMetrics: EvalMetric[] = [
  { name: '执行时长', value: 8.2, unit: 's', status: 'good' },
  { name: '准确度', value: 94.5, unit: '%', status: 'good' },
  { name: '内存使用', value: 156, unit: 'MB', status: 'good' },
  { name: '工具调用', value: 3, unit: '次', status: 'good' },
];
