"""Type definitions for the Agent module."""

from collections import Counter
from dataclasses import dataclass
from dataclasses import field
from datetime import datetime
from enum import Enum
from typing import Any, Callable, Dict, List, Optional
from uuid import uuid4

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field


@dataclass
class AgentDefinition:
    """Parsed agent definition from markdown with YAML frontmatter.

    Attributes:
        name: Unique identifier for the agent.
        description: Human-readable description of what the agent does.
        tools: List of tools the agent can use.
        system_prompt: System prompt content (body of the markdown file).
        skills: List of skill names loaded into the system prompt.
        max_iterations: Maximum tool-call iterations for the execution loop.
            Used by ToolExecutor (LLM path) and as max_turns for the Claude
            SDK path. Defaults to 10. Set higher for research-heavy agents.
    """

    name: str
    description: str = ""
    tools: List[str] = field(default_factory=list)
    system_prompt: str = ""
    skills: List[str] = field(default_factory=list)
    max_iterations: int = 10

    @property
    def agent_id(self) -> str:
        """Alias for name, for backward compatibility."""
        return self.name


class AgentState(BaseModel):
    """Agent state for persistence.

    Attributes:
        agent_id: Unique identifier for the agent.
        status: Current agent status (one of STATUS_* constants).
        current_task: Description of the current task being processed.
    """

    agent_id: str
    status: str = 'idle'
    current_task: Optional[str] = None


class AgentTask(BaseModel):
    """Task specification for Agent execution.

    This class provides a type-safe interface for agent task inputs,
    with support for multimodal content (images) and arbitrary metadata.

    Attributes:
        description: Human-readable task description.
        base_dir: Base directory for resolving relative image paths.
        image_path: Single image path for the task.
        image_paths: List of image paths for the task.
        images: List of image paths.
    """

    model_config = ConfigDict(extra="allow")  # Allow additional fields

    description: str = Field(
        default="Process the following data",
        description="Human-readable task description",
    )
    workspace_dir: Optional[str] = Field(
        default=None,
        description="Workspace directory for the task",
    )
    image_path: Optional[str] = Field(
        default=None,
        description="Single image path for the task",
    )
    image_paths: Optional[List[str]] = Field(
        default=None,
        description="List of image paths for the task",
    )
    images: Optional[List[str]] = Field(
        default=None,
        description="List of image paths",
    )

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "AgentTask":
        """Create AgentTask from a dictionary.

        Args:
            data: Task data dictionary.

        Returns:
            AgentTask instance.
        """
        return cls(**data)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary, excluding None values.

        Returns:
            Dictionary representation of the task.
        """
        return self.model_dump(exclude_none=True)

    def get_extra_fields(self) -> Dict[str, Any]:
        """Get all extra fields not defined in the model.

        Returns:
            Dictionary of extra fields.
        """
        defined_fields = set(self.model_fields.keys())
        return {k: v for k, v in self.model_dump().items() if k not in defined_fields}


# ======================================================================
# Plan Mode Types
# ======================================================================


class AgentMode(str, Enum):
    """Agent execution mode.

    Attributes:
        DIRECT: Execute the task immediately via LLM loop (existing behavior).
        PLAN: Decompose the goal into structured tasks first, then execute.
    """

    DIRECT = "direct"
    PLAN = "plan"


class TaskStatus(str, Enum):
    """Status of a planned task.

    Attributes:
        PENDING: Task has not started.
        IN_PROGRESS: Task is currently executing.
        COMPLETED: Task finished successfully.
        FAILED: Task failed.
        SKIPPED: Task was skipped.
    """

    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


class PlannedTask(BaseModel):
    """A single task within a plan.

    Generated by the Agent in plan mode, or manually constructed
    for pre-defined workflows (SOP is a special case where tasks
    are authored by humans instead of an LLM).

    Attributes:
        task_id: Unique identifier for this task.
        description: What this task should accomplish.
        reasoning: Why this task is needed (LLM-generated rationale).
        dependencies: List of task_ids that must complete before this one.
        agent_id: Optional agent to delegate to (None = self).
        tools: Optional tool allowlist for this task.
        inputs: Structured input data for the task.
        expected_output: Description of desired output.
        status: Current execution status.
        result: Output data after completion.
        error: Error message if failed.
    """

    task_id: str
    description: str
    reasoning: Optional[str] = None
    dependencies: List[str] = Field(default_factory=list)
    agent_id: Optional[str] = None
    action: str = "process"
    tools: Optional[List[str]] = None
    inputs: Dict[str, Any] = Field(default_factory=dict)
    expected_output: Optional[str] = None
    retry_count: int = Field(default=0, ge=0)
    optional: bool = False
    status: TaskStatus = TaskStatus.PENDING
    result: Optional[Dict[str, Any]] = None
    error: Optional[str] = None

    def is_ready(self, completed_ids: set) -> bool:
        """Check if all dependencies are met.

        Args:
            completed_ids: Set of completed task IDs.

        Returns:
            True if all dependencies are satisfied.
        """
        return all(dep in completed_ids for dep in self.dependencies)


class Plan(BaseModel):
    """A structured plan — the base abstraction for task orchestration.

    A Plan is a DAG of PlannedTasks with dependency tracking.
    It can be created dynamically by an LLM (plan mode) or
    pre-defined by a human (SOP is a special case that skips
    the LLM planning step).

    Attributes:
        plan_id: Unique identifier for this plan.
        goal: The original user goal / request.
        summary: Brief overview of the plan strategy.
        tasks: Ordered list of tasks to execute.
        status: Lifecycle status of the plan.
        created_at: When the plan was created.
        updated_at: When the plan was last modified.
    """

    plan_id: str = Field(default_factory=lambda: f"plan_{uuid4().hex[:8]}")
    goal: str = ""
    summary: str = ""
    tasks: List[PlannedTask] = Field(default_factory=list)
    max_parallel: int = Field(default=10, ge=1)
    default_retry_count: int = Field(default=0, ge=0)
    status: str = "draft"  # draft -> approved -> executing -> completed -> failed
    created_at: datetime = Field(default_factory=datetime.now)
    updated_at: Optional[datetime] = None

    def get_next_tasks(self) -> List[PlannedTask]:
        """Get tasks that are ready to execute.

        A task is ready when all its dependencies have completed
        and the task itself is still pending.

        Returns:
            List of tasks ready for execution.
        """
        completed_ids = {
            t.task_id
            for t in self.tasks if t.status == TaskStatus.COMPLETED
        }
        return [
            t for t in self.tasks
            if t.status == TaskStatus.PENDING and t.is_ready(completed_ids)
        ]

    def get_progress(self) -> Dict[str, int]:
        """Get plan progress summary.

        Returns:
            Dictionary with counts per status.
        """
        counts = Counter(t.status for t in self.tasks)
        return {
            "total": len(self.tasks),
            "completed": counts.get(TaskStatus.COMPLETED, 0),
            "failed": counts.get(TaskStatus.FAILED, 0),
            "pending": counts.get(TaskStatus.PENDING, 0),
            "in_progress": counts.get(TaskStatus.IN_PROGRESS, 0),
        }

    def is_complete(self) -> bool:
        """Check if the plan has finished (all tasks done or failed).

        Returns:
            True if no tasks are pending or in progress.
        """
        return all(t.status in (TaskStatus.COMPLETED, TaskStatus.FAILED,
                                TaskStatus.SKIPPED) for t in self.tasks)

    def get_task(self, task_id: str) -> Optional[PlannedTask]:
        """Find a task by ID.

        Args:
            task_id: The task ID to look up.

        Returns:
            The PlannedTask or None if not found.
        """
        for task in self.tasks:
            if task.task_id == task_id:
                return task
        return None
