TERMS = {
    "Planning": ["literature review", "background", "prior work", "objective"],
    "Design": [
        "active site",
        "sequence design",
        "computational design",
        "de novo",
        "docking",
        "scoring function",
        "molecular dynamics",
        "MD simulation",
        "structural modeling",
    ],
    "Construction": [
        "mutagenesis",
        "site-directed",
        "library construction",
        "cloning",
        "vector",
        "transformation",
    ],
    "Expression": [
        "expression",
        "culture",
        "fermentation",
        "induction",
        "purification",
        "SDS-PAGE",
    ],
    "Assay": [
        "kinetic assay",
        "Km",
        "kcat",
        "activity",
        "substrate",
        "buffer",
        "temperature",
    ],
    "Optimization": [
        "directed evolution",
        "rounds",
        "screening",
        "selection",
        "fitness",
        "improvement",
    ],
}

CATEGORY_ZH = {
    "Planning": "规划与调研",
    "Design": "设计（保留术语）",
    "Construction": "构建与突变",
    "Expression": "表达与纯化",
    "Assay": "测定与表征",
    "Optimization": "优化与进化",
}
